baseurl             = "https://siokcronin.github.io/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "docs"
theme               = "cocoa"
author              = "Siobhan K Cronin"
title               = "Siobhan K Cronin"
pygmentsuseclasses  = true
# disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
# googleAnalytics     = "UA-123-45"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "about/"

[[menu.main]]
name                   = "ML/AI"
weight                 = -100
identifier             = "machine learning"
url                    = "ai_notes/"

[[menu.main]]
name                   = "Speaking"
weight                 = -100
identifier             = "speaking"
url                    = "speaking/"

[params]
include_rss            = false                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Siobhan K Cronin"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Siobhan K Cronin is a machine learning engineer, researcher, and public speaker"
email                  = "siobhankcronin@gmail.com"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/siokcronin"
lang                   = "en"
linkedin               = "//linkedin.com/in/siobhankcronin"
medium                 = "//medium.com/@siobhankcronin"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/siokcronin"
highlightjs            = true

piwik                  = false                         # If true, Piwik integration is enabled
gitalk                 = false                         # if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth

avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
