title = "Siobhán K Cronin"
baseURL = "https://siokcronin.github.io/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "ai_notes"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/override.css"]
  highlightjs = true
  highlightjslanguages = ["python"]
  mainSections = ["posts"]
  favicon = ""
  description = "Siobhán K Cronin is a machine learning engineer, researcher, and public speaker"
  facebook = ""
  twitter = "//twitter.com/siokcronin"
  instagram = ""
  youtube = ""
  github = "//github.com/siokcronin"
  linkedin = "//linkedin.com/in/siobhankcronin"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-yellow"
  featured_image = false
  recent_posts_number = 10

[menu]
    [[menu.main]]
    identifier = "speaking"
    name       = "Speaking"
    url        = "/speaking"
    weight     = 0

    [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"
    weight     = 1

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 2

