title = "Siobhán K Cronin"
baseURL = "https://siobhankcronin.com/"
publishDir = "docs"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "ai_notes"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  env = "production"
  custom_css = ["css/override.css"]
  highlightjs = true
  highlightjslanguages = ["python"]
  mainSections = ["posts"]
  favicon = ""
  description = "Siobhán K Cronin is a software engineer, researcher, and public speaker"
  facebook = ""
  twitter = "//twitter.com/siokcronin"
  instagram = ""
  youtube = ""
  github = "//github.com/siokcronin"
  linkedin = "//linkedin.com/in/siobhankcronin"
  medium = "//medium.com/@siobhankcronin"
  background_color_class = "bg-sio-yellow"
  body_classes = "avenir bg-white-90"
  featured_image = false
  recent_posts_number = 10

[menu]

    [[menu.main]]
    identifier = "studio"
    name       = "Studio"
    url        = "/studio"
    weight     = 5

    [[menu.main]]
    identifier = "meditation"
    name       = "Meditation"
    url        = "/meditation"
    weight     = 4

    [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "/index.html"
    weight     = 3

    [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "/cv"
    weight     = 2

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 1

    [[menu.main]]
    identifier = "meditation"
    name       = "Meditation"
    url        = "/meditation"
    weight     = 4

    [[menu.main]]
    identifier = "notes"
    name       = "Notes"
    url        = "/index.html"
    weight     = 3

    [[menu.main]]
    identifer = "mvmt"
    name      = "mvmt"
    url       = "/mvmt"
    weight    = 2

    [[menu.main]]
    identifier = "cv"
    name       = "CV"
    url        = "/cv"
    weight     = 2

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 1

